language: python
python:
  - 3.4
services:
  - postgresql
env:
  - DEBUG=True
install:
  - pip install -q -r requirements.txt
  - pip install -q -e .
before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
  - cp config/database.yml.travis config/database.yml
script:
  - python src/api/create_db.py
  - sh src/api/test/test.sh